travelMonitor: travelMonitor.cpp Monitor.cpp hw/skip.h hw/country.h hw/bloom.h hw/person.h
	g++ travelMonitor.cpp hw/bloom.cpp -o travelMonitor -std=c++11
	g++ Monitor.cpp hw/skip.cpp hw/country.cpp hw/bloom.cpp hw/person.cpp -o Monitor -std=c++11
clean:
	rm travelMonitor
	rm Monitor